### PR TITLE
Don't overwrite identity json when enrolling

### LINKED ISSUE #268: ziti-edge-tunnel: enroll should not overwrite json file on failure
right now issuing `ziti-edge-tunnel enroll -j jwt.file -i identity.file` twice will work the first time, then fail the second time. if you make this mistake you MUST recreate your identity file. it would be much better to not overwrite this file if the command is run twice

### LINKED ISSUE #516: ziti-edge-tunnel enroll fails silently if identity dir is not writeable
Expected: error message like "ERROR: unable to write identity file in /path/to/identity/dir/config.json, permission denied"
Observed: errexit code 255 is the only clue that enrollment failed

I encountered this in v0.20.0

### LINKED ISSUE #532: enroll command fails unless enroll_key is provided
The fix for #528 added logic to check that required enroll arguments were provided. The logic erroneously checks for the enrollment key instead of the output file.

### PR DESCRIPTION
**Pull request by scareything**
fixes #268
fixes #532
fixes #516

### CODE REVIEW

**Review by smilindave26 — APPROVED** [review]

File: programs/ziti-edge-tunnel/ziti-edge-tunnel.c [hunk 1]
```diff
@@ -2018,6 +2025,10 @@ static void enroll_cb(ziti_config *cfg, int status, char *err, void *ctx) {
 }
 
 static void enroll(int argc, char *argv[]) {
+    uv_loop_t *l = uv_loop_new();
```
Comment (dovholuknf) [inline programs/ziti-edge-tunnel/ziti-edge-tunnel.c:2028]: `process_tunnel_commands` calls `enroll_ziti_async` which calls this function. is it appropriate to get the log level and log init here?

Comment (dovholuknf) [reply programs/ziti-edge-tunnel/ziti-edge-tunnel.c:2028]: also seems like `enroll` should take the loop?

Comment (dovholuknf) [reply programs/ziti-edge-tunnel/ziti-edge-tunnel.c:2028]: nevermind. it uses `ziti_enroll` instead. my bad! :) lgtm

**Review by dovholuknf — APPROVED** [review]
