### PR TITLE
Send RST to client when closing un-established connections

### LINKED ISSUE #491: intercepted tcp connections must traverse wait states when ziti_dial fails
We currently close the lwip connection when ziti_dial fails for any reason.

The lwip-side of the client connection is in `SYN_RCVD` until ziti_dial succeeds; so closing the connection (with `tcp_close`) while in this state puts the lwip connection into `FIN_WAIT1`. Now the client is probably confused (rightfully so) and will not send FIN, etc. so the lwip side goes through all of the wait states, and the associated PCB is retained until the timeouts elapse.

### PR DESCRIPTION
**Pull request by scareything**
closes #491

### CODE REVIEW

File: lib/ziti-tunnel/tunnel_tcp.c [hunk 1]
```diff
@@ -236,6 +236,11 @@ int tunneler_tcp_close(struct tcp_pcb *pcb) {
     }
     tcp_arg(pcb, NULL);
     tcp_recv(pcb, NULL);
+    if (pcb->state <= ESTABLISHED) {
```
Comment (ekoby) [inline lib/ziti-tunnel/tunnel_tcp.c]: should this be `< ESTABLISHED`?

Comment (ekoby) [reply lib/ziti-tunnel/tunnel_tcp.c]: looks like it was changed

**Review by ekoby — APPROVED** [review]
lgtm
